/* This file was generated by SableCC (http://www.sablecc.org/). */

package analysis;

import java.util.*;
import node.*;

public class AnalysisAdapter implements Analysis
{
    private Hashtable<Node,Object> in;
    private Hashtable<Node,Object> out;

    public Object getIn(Node node)
    {
        if(this.in == null)
        {
            return null;
        }

        return this.in.get(node);
    }

    public void setIn(Node node, Object o)
    {
        if(this.in == null)
        {
            this.in = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.in.put(node, o);
        }
        else
        {
            this.in.remove(node);
        }
    }

    public Object getOut(Node node)
    {
        if(this.out == null)
        {
            return null;
        }

        return this.out.get(node);
    }

    public void setOut(Node node, Object o)
    {
        if(this.out == null)
        {
            this.out = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.out.put(node, o);
        }
        else
        {
            this.out.remove(node);
        }
    }

    public void caseTDigito(TDigito node)
    {
        defaultCase(node);
    }

    public void caseTAspasSimples(TAspasSimples node)
    {
        defaultCase(node);
    }

    public void caseTVirgula(TVirgula node)
    {
        defaultCase(node);
    }

    public void caseTPonto(TPonto node)
    {
        defaultCase(node);
    }

    public void caseTDoisPontos(TDoisPontos node)
    {
        defaultCase(node);
    }

    public void caseTPontoVirgula(TPontoVirgula node)
    {
        defaultCase(node);
    }

    public void caseTLPar(TLPar node)
    {
        defaultCase(node);
    }

    public void caseTRPar(TRPar node)
    {
        defaultCase(node);
    }

    public void caseTLColc(TLColc node)
    {
        defaultCase(node);
    }

    public void caseTRColc(TRColc node)
    {
        defaultCase(node);
    }

    public void caseTMult(TMult node)
    {
        defaultCase(node);
    }

    public void caseTDiv(TDiv node)
    {
        defaultCase(node);
    }

    public void caseTMais(TMais node)
    {
        defaultCase(node);
    }

    public void caseTMenos(TMenos node)
    {
        defaultCase(node);
    }

    public void caseTAtribuicao(TAtribuicao node)
    {
        defaultCase(node);
    }

    public void caseTIgLog(TIgLog node)
    {
        defaultCase(node);
    }

    public void caseTDifLog(TDifLog node)
    {
        defaultCase(node);
    }

    public void caseTMenor(TMenor node)
    {
        defaultCase(node);
    }

    public void caseTMenorIg(TMenorIg node)
    {
        defaultCase(node);
    }

    public void caseTMaior(TMaior node)
    {
        defaultCase(node);
    }

    public void caseTMaiorIg(TMaiorIg node)
    {
        defaultCase(node);
    }

    public void caseTE(TE node)
    {
        defaultCase(node);
    }

    public void caseTOu(TOu node)
    {
        defaultCase(node);
    }

    public void caseTNao(TNao node)
    {
        defaultCase(node);
    }

    public void caseTPrograma(TPrograma node)
    {
        defaultCase(node);
    }

    public void caseTVar(TVar node)
    {
        defaultCase(node);
    }

    public void caseTInicio(TInicio node)
    {
        defaultCase(node);
    }

    public void caseTFim(TFim node)
    {
        defaultCase(node);
    }

    public void caseTSe(TSe node)
    {
        defaultCase(node);
    }

    public void caseTEnquanto(TEnquanto node)
    {
        defaultCase(node);
    }

    public void caseTPara(TPara node)
    {
        defaultCase(node);
    }

    public void caseTEntao(TEntao node)
    {
        defaultCase(node);
    }

    public void caseTFaca(TFaca node)
    {
        defaultCase(node);
    }

    public void caseTSenao(TSenao node)
    {
        defaultCase(node);
    }

    public void caseTRepita(TRepita node)
    {
        defaultCase(node);
    }

    public void caseTAte(TAte node)
    {
        defaultCase(node);
    }

    public void caseTEscreva(TEscreva node)
    {
        defaultCase(node);
    }

    public void caseTCaractere(TCaractere node)
    {
        defaultCase(node);
    }

    public void caseTInteiro(TInteiro node)
    {
        defaultCase(node);
    }

    public void caseTReal(TReal node)
    {
        defaultCase(node);
    }

    public void caseTString(TString node)
    {
        defaultCase(node);
    }

    public void caseTBranco(TBranco node)
    {
        defaultCase(node);
    }

    public void caseTId(TId node)
    {
        defaultCase(node);
    }

    public void caseTComentario(TComentario node)
    {
        defaultCase(node);
    }

    public void caseEOF(EOF node)
    {
        defaultCase(node);
    }

    public void defaultCase(@SuppressWarnings("unused") Node node)
    {
        // do nothing
    }
}
